package ru.itis.desktop.text

internal object DesktopSettingsText {
    const val TITLE = "UI Analyzer"
    const val SUBTITLE = "Desktop control panel"
    const val ANDROID_PROJECT = "Android project"
    const val REPORT_OUTPUT = "Report output"
    const val MODE = "Mode"
    const val STATIC_TITLE = "Static"
    const val STATIC_DESCRIPTION = "Analyze XML and Compose sources."
    const val STATIC_ICON = "ST"
    const val RUNTIME_TITLE = "Runtime"
    const val RUNTIME_DESCRIPTION = "Capture actual UI bounds from device."
    const val RUNTIME_ICON = "RT"
    const val SOURCE = "Source"
    const val XML_COMPOSE_TITLE = "XML + Compose"
    const val XML_COMPOSE_DESCRIPTION = "Run both static rule sets."
    const val XML_COMPOSE_ICON = "A"
    const val XML_TITLE = "XML"
    const val XML_DESCRIPTION = "Layout resources only."
    const val XML_ICON = "X"
    const val COMPOSE_TITLE = "Compose"
    const val COMPOSE_DESCRIPTION = "Kotlin UI sources only."
    const val COMPOSE_ICON = "C"
    const val RUNTIME_SNAPSHOT = "Runtime snapshot"
    const val ADB_TITLE = "ADB"
    const val ADB_DESCRIPTION = "Capture from emulator or device."
    const val ADB_ICON = "ADB"
    const val FILE_TITLE = "File"
    const val FILE_DESCRIPTION = "Use saved runtime snapshot."
    const val FILE_ICON = "JS"
    const val ADB_SERIAL = "ADB serial, optional"
    const val RUNTIME_SNAPSHOT_FILE = "Runtime snapshot file"
}
