package ru.itis.analyzer.config.components

object ComponentTypes {
    const val TEXT_VIEW = "TextView"
    const val BUTTON = "Button"
    const val MATERIAL_BUTTON = "MaterialButton"
    const val IMAGE_VIEW = "ImageView"
    const val IMAGE_BUTTON = "ImageButton"
    const val LINEAR_LAYOUT = "LinearLayout"
    const val CONSTRAINT_LAYOUT = "ConstraintLayout"
    const val FRAME_LAYOUT = "FrameLayout"
    const val RELATIVE_LAYOUT = "RelativeLayout"
    const val SCROLL_VIEW = "ScrollView"
    const val HORIZONTAL_SCROLL_VIEW = "HorizontalScrollView"
    const val ANDROIDX_CONSTRAINT_LAYOUT = "androidx.constraintlayout.widget.ConstraintLayout"
    const val ANDROID_WIDGET_IMAGE_VIEW = "android.widget.ImageView"
    const val ANDROID_WIDGET_IMAGE_BUTTON = "android.widget.ImageButton"
    const val APP_COMPAT_IMAGE_VIEW = "AppCompatImageView"
    const val APP_COMPAT_IMAGE_BUTTON = "AppCompatImageButton"
    const val ANDROIDX_APP_COMPAT_IMAGE_VIEW = "androidx.appcompat.widget.AppCompatImageView"
    const val ANDROIDX_APP_COMPAT_IMAGE_BUTTON = "androidx.appcompat.widget.AppCompatImageButton"

    const val COMPOSE_TEXT = "Text"
    const val COMPOSE_BUTTON = "Button"
    const val COMPOSE_ICON_BUTTON = "IconButton"
    const val COMPOSE_OUTLINED_BUTTON = "OutlinedButton"
    const val COMPOSE_TEXT_BUTTON = "TextButton"
    const val COMPOSE_FLOATING_ACTION_BUTTON = "FloatingActionButton"
    const val COMPOSE_IMAGE = "Image"
    const val COMPOSE_ICON = "Icon"
    const val COMPOSE_COLUMN = "Column"
    const val COMPOSE_ROW = "Row"
    const val COMPOSE_BOX = "Box"
    const val COMPOSE_LAZY_COLUMN = "LazyColumn"
    const val COMPOSE_LAZY_ROW = "LazyRow"
    const val COMPOSE_SURFACE = "Surface"
    const val COMPOSE_CARD = "Card"
    const val COMPOSE_SPACER = "Spacer"

    const val TEXT_VIEW_SUFFIX = "TextView"
    const val BUTTON_SUFFIX = "Button"
    const val IMAGE_VIEW_SUFFIX = "ImageView"
    const val IMAGE_BUTTON_SUFFIX = "ImageButton"
}